/**
 * Mock Museum Data for ArtGuard AI Security System
 * Simulates a Louvre-style museum with security infrastructure
 */ 

export const museumData = {
  // Security Cameras
  cameras: [
    {
      id: 1,
      name: "CAM-01 | Main Entrance",
      room: "Main Lobby",
      status: "active",
      peopleCount: 24,
      location: { x: 50, y: 20 },
      hasMotionDetection: true,
      lastActivity: "30 seconds ago",
      floorMapKey: "mainGallery" // <-- added for AnimatedCamera
    },
    {
      id: 2,
      name: "CAM-02 | Mona Lisa Gallery",
      room: "Gallery 3",
      status: "active",
      peopleCount: 18,
      location: { x: 120, y: 80 },
      hasMotionDetection: true,
      lastActivity: "1 minute ago",
      floorMapKey: "mainGallery"
    },
    {
      id: 3,
      name: "CAM-03 | Egyptian Wing",
      room: "Gallery 7",
      status: "active",
      peopleCount: 12,
      location: { x: 200, y: 100 },
      hasMotionDetection: true,
      lastActivity: "45 seconds ago",
      floorMapKey: "storageRoom"
    },
    {
      id: 4,
      name: "CAM-04 | Loading Dock",
      room: "Service Area",
      status: "offline",
      peopleCount: 0,
      location: { x: 300, y: 150 },
      hasMotionDetection: true,
      lastActivity: "15 minutes ago",
      floorMapKey: "storageRoom"
    },
    {
      id: 5,
      name: "CAM-05 | Sculpture Garden",
      room: "Outdoor Plaza",
      status: "active",
      peopleCount: 8,
      location: { x: 150, y: 200 },
      hasMotionDetection: true,
      lastActivity: "2 minutes ago",
      floorMapKey: "sculptureHall"
    },
    {
      id: 6,
      name: "CAM-06 | Crown Jewels Vault",
      room: "High Security Vault",
      status: "active",
      peopleCount: 2,
      location: { x: 250, y: 50 },
      hasMotionDetection: true,
      lastActivity: "10 seconds ago",
      floorMapKey: "securityOffice"
    }
  ],

  // Security Guards
  guards: [
    {
      id: 1,
      name: "Guard Martinez",
      location: "Main Entrance",
      room: "Main Lobby",
      status: "on-duty",
      lastCheckIn: "2 minutes ago",
      position: { x: 55, y: 25 },
      badge: "SEC-001",
      yearsExperience: 8
    },
    {
      id: 2,
      name: "Guard Chen",
      location: "Gallery 3 - Egyptian Wing",
      room: "Gallery 3",
      status: "on-duty",
      lastCheckIn: "1 minute ago",
      position: { x: 125, y: 85 },
      badge: "SEC-002",
      yearsExperience: 5
    },
    {
      id: 3,
      name: "Guard Johnson",
      location: "Break Room",
      room: "Staff Area",
      status: "break",
      lastCheckIn: "8 minutes ago",
      position: { x: 180, y: 180 },
      badge: "SEC-003",
      yearsExperience: 12
    },
    {
      id: 4,
      name: "Guard Dubois",
      location: "Crown Jewels Vault",
      room: "High Security Vault",
      status: "on-duty",
      lastCheckIn: "30 seconds ago",
      position: { x: 255, y: 55 },
      badge: "SEC-004",
      yearsExperience: 15
    }
  ],

  // Active Security Alerts
  alerts: [
    {
      id: 1,
      severity: "medium",
      type: "motion",
      message: "Unusual motion pattern detected in Gallery 3",
      location: "Gallery 3 - Egyptian Wing",
      camera: 2,
      timestamp: "2 minutes ago",
      status: "investigating",
      autoGenerated: true
    },
    {
      id: 2,
      severity: "low",
      type: "system",
      message: "Camera 4 offline - maintenance required",
      location: "Loading Dock",
      camera: 4,
      timestamp: "15 minutes ago",
      status: "acknowledged",
      autoGenerated: true
    },
    {
      id: 3,
      severity: "high",
      type: "access",
      message: "After-hours access attempt - Crown Jewels Vault",
      location: "High Security Vault",
      camera: 6,
      timestamp: "30 seconds ago",
      status: "active",
      autoGenerated: true
    }
  ],

  // Museum Rooms/Galleries
  rooms: [
    {
      id: 1,
      name: "Main Lobby",
      visitorCount: 45,
      capacity: 100,
      threatLevel: "low",
      cameras: [1],
      guards: [1],
      status: "open",
      valuableArtworks: 0
    },
    {
      id: 2,
      name: "Gallery 3 - Renaissance Paintings",
      visitorCount: 32,
      capacity: 50,
      threatLevel: "medium",
      cameras: [2],
      guards: [2],
      status: "open",
      valuableArtworks: 12,
      featuredArt: ["Mona Lisa", "The Wedding at Cana"]
    },
    {
      id: 3,
      name: "Gallery 7 - Egyptian Antiquities",
      visitorCount: 18,
      capacity: 40,
      threatLevel: "low",
      cameras: [3],
      guards: [],
      status: "open",
      valuableArtworks: 24
    },
    {
      id: 4,
      name: "High Security Vault",
      visitorCount: 0,
      capacity: 10,
      threatLevel: "high",
      cameras: [6],
      guards: [4],
      status: "restricted",
      valuableArtworks: 8,
      featuredArt: ["Crown Jewels of France", "Regent Diamond"]
    },
    {
      id: 5,
      name: "Sculpture Garden",
      visitorCount: 22,
      capacity: 80,
      threatLevel: "low",
      cameras: [5],
      guards: [],
      status: "open",
      valuableArtworks: 6
    },
    {
      id: 6,
      name: "Loading Dock",
      visitorCount: 0,
      capacity: 20,
      threatLevel: "low",
      cameras: [4],
      guards: [],
      status: "service",
      valuableArtworks: 0
    }
  ],

  // System Status
  system: {
    status: "operational",
    uptime: "99.8%",
    lastMaintenance: "3 days ago",
    totalCameras: 6,
    activeCameras: 5,
    totalGuards: 4,
    onDutyGuards: 3,
    totalAlerts: 3,
    criticalAlerts: 1,
    currentThreatLevel: "medium"
  },

  // Recent Activity Log (for status reports)
  recentActivity: [
    {
      id: 1,
      time: "30 seconds ago",
      type: "alert",
      message: "Access attempt detected - Crown Jewels Vault",
      severity: "high"
    },
    {
      id: 2,
      time: "1 minute ago",
      type: "guard",
      message: "Guard Chen checked in at Gallery 3",
      severity: "info"
    },
    {
      id: 3,
      time: "2 minutes ago",
      type: "camera",
      message: "Motion pattern analyzed - Gallery 3",
      severity: "medium"
    },
    {
      id: 4,
      time: "2 minutes ago",
      type: "guard",
      message: "Guard Martinez checked in at Main Entrance",
      severity: "info"
    },
    {
      id: 5,
      time: "8 minutes ago",
      type: "guard",
      message: "Guard Johnson started break",
      severity: "info"
    }
  ]
};

// Helper functions
export const getCameraById = (id: number) => {
  return museumData.cameras.find(camera => camera.id === id);
};

export const getGuardByName = (name: string) => {
  return museumData.guards.find(guard => 
    guard.name.toLowerCase().includes(name.toLowerCase())
  );
};

export const getAlertsBySeverity = (severity: string) => {
  return museumData.alerts.filter(alert => alert.severity === severity);
};

export const getRoomByName = (name: string) => {
  return museumData.rooms.find(room => 
    room.name.toLowerCase().includes(name.toLowerCase())
  );
};

export default museumData;
